---
title: "Plots"
output: html_notebook
---

NEAT Generation Plots
```{r, fig.keep='all'}
library(ggplot2)
library(tidyverse)
library(dplyr)

neat.dynamic<- read.csv('finalists/neat_dynamic_4_13.csv')
neat.static<- read.csv('finalists/neat_static_4_13.csv')


#neat.dynamic.mean
ggplot(neat.dynamic, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=neat.dynamic$minFitness, ymax=neat.dynamic$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "NEAT Dynamic (Mean), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#neat.dynamic.median
ggplot(neat.dynamic, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=neat.dynamic$minFitness, ymax=neat.dynamic$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "NEAT Dynamic (Median), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#neat.static.mean
ggplot(neat.static, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=neat.static$minFitness, ymax=neat.static$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "NEAT Static (Mean), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#neat.static.median
ggplot(neat.static, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=neat.static$minFitness, ymax=neat.static$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "NEAT Static (Median), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
ann.dynamic<- read.csv('finalists/ann_dynamic_4_15.csv')
ann.static<- read.csv('finalists/ann_static_4_15.csv')

#ann.dynamic.mean
ggplot(ann.dynamic, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.dynamic$minFitness, ymax=ann.dynamic$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Dynamic (Mean), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#ann.dynamic.median
ggplot(ann.dynamic, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.dynamic$minFitness, ymax=ann.dynamic$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Dynamic (Median), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#ann.static.mean
ggplot(ann.static, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.static$minFitness, ymax=ann.static$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Static (Mean), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
#ann.static.median
ggplot(ann.static, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.static$minFitness, ymax=ann.static$maxFitness), width = .2)+
  ylim(0, 20000)+
  theme_classic()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Static (Median), 100 Generations", x= "Generation", y= "Fitness")
```

```{r}
ann.static.500<- read.csv('finalists/ann_static_500.csv')

#ann.static.mean
ggplot(ann.static.500, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.static.500$minFitness, ymax=ann.static.500$maxFitness), width = .1)+
 ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Static (Mean), 500 Generations", x= "Generation", y= "Fitness")
```

```{r}

#ann.static.median
ggplot(ann.static.500, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.static.500$minFitness, ymax=ann.static.500$maxFitness), width = .1)+
 ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Static (Median), 500 Generations", x= "Generation", y= "Fitness")
```

```{r}
ann.dynamic.500<- read.csv('finalists/ann_dynamic_500.csv')

#ann.dynamic.mean
ggplot(ann.dynamic.500, aes(x=generation, y= meanFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.dynamic.500$minFitness, ymax=ann.dynamic.500$maxFitness), width = .1)+
 ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Dynamic (Mean), 500 Generations", x= "Generation", y= "Fitness")
```

```{r}
#ann.dynamic.median
ggplot(ann.dynamic.500, aes(x=generation, y= medianFitness)) + 
  geom_point()+
   geom_errorbar(aes(ymin=ann.dynamic.500$minFitness, ymax=ann.dynamic.500$maxFitness), width = .1)+
 ylim(0, 20000)+
  theme_bw()+
  geom_smooth(method='lm', formula= y~x)+
  labs(title= "ANN Dynamic (Median), 500 Generations", x= "Generation", y= "Fitness")
```

```{r}
library(dplyr)
neat.static.weights<- read.csv('finalists/neat_static_weights.csv')
neat.dynamic.weights<- read.csv('finalists/neat_dynamic_weights.csv')


dynamic.weight.descriptors<- neat.dynamic.weights %>%
  select(V51, V52, V53, V54)

output.node<- c('Forwards', 'Backwards', 'TurnClock', 'TurnCounter')
nonZero<- colSums(dynamic.weight.descriptors != 0)
zero<- colSums(dynamic.weight.descriptors == 0)
positive<- colSums(dynamic.weight.descriptors > 0)
negative<- colSums(dynamic.weight.descriptors < 0)
strong<- colSums(dynamic.weight.descriptors > 1)

dynamic.w.summary<- data.frame(output.node, nonZero, zero, positive, negative, strong)


  
static.weight.descriptors<- neat.static.weights %>%
  select(V51, V52, V53, V54)
output.node<- c('Forwards', 'Backwards', 'TurnClock', 'TurnCounter')
nonZero<- colSums(static.weight.descriptors != 0)
zero<- colSums(static.weight.descriptors == 0)
positive<- colSums(static.weight.descriptors > 0)
negative<- colSums(static.weight.descriptors < 0)
strong<- colSums(static.weight.descriptors > 1)

static.w.summary<- data.frame(output.node, nonZero, zero, positive, negative, strong)

write.csv(static.w.summary,"finalists/neat_static_w_sum.csv", row.names = T)
write.csv(dynamic.w.summary,"finalists/neat_dynamic_w_sum.csv", row.names = T)

```
LightGrid Vis
```{r}

d1
write.csv(d1,"finalists/5x20.csv", row.names = T)
d2
write.csv(d2,"finalists/4x25.csv", row.names = T)
d3
write.csv(d3,"finalists/10x10.csv", row.names = T)
d4<- makeGrids(2)
d4
write.csv(d4,"finalists/24x4.csv", row.names = T)
d5<- makeGrids(2)
d5
write.csv(d5,"finalists/20x5.csv", row.names = T)
```
